[alias]
fc = "fmt --all -- --check"
cw = "clippy --workspace  --all-features --all-targets -- --deny warnings -W clippy::pedantic"
tw = "test --workspace --all-features --all-targets"
twdoc = "test --workspace --doc"
ct = "run --release --example crash-test -- --clean"
bp = "bench --package lib-kifa"

# reduces binary size by 27%
# This breaks some crates that rely on unwinding for error handling when running the crash test and benches.
# [profile.release]
# panic = "immediate-abort"

# [unstable]
# panic-immediate-abort = true
# build-std = ["std", "panic_abort"]
# build-std-features = ["optimize_for_size"]
